// <auto-generated />
using System;
using DevFlow.Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevFlow.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260724092627_AddMultiFactorAuthentication")]
    partial class AddMultiFactorAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevFlow.Identity.Domain.Authentication.EmailVerificationTokens.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("UsedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("EmailVerificationTokens", "identity");
                });

            modelBuilder.Entity("DevFlow.Identity.Domain.Authentication.PasswordResetTokens.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UsedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("PasswordResetTokens", "identity");
                });

            modelBuilder.Entity("DevFlow.Identity.Domain.Authentication.RefreshTokens.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "identity");
                });

            modelBuilder.Entity("DevFlow.Identity.Domain.Authentication.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("DevFlow.Identity.Domain.Authentication.RefreshTokens.RefreshToken", b =>
                {
                    b.HasOne("DevFlow.Identity.Domain.Authentication.Users.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevFlow.Identity.Domain.Authentication.Users.User", b =>
                {
                    b.OwnsOne("DevFlow.Identity.Domain.Authentication.Users.ValueObjects.MultiFactorSettings", "MultiFactor", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("boolean")
                                .HasColumnName("TwoFactorEnabled");

                            b1.Property<DateTime?>("EnabledOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("TwoFactorEnabledOnUtc");

                            b1.Property<bool>("Pending")
                                .HasColumnType("boolean")
                                .HasColumnName("TwoFactorPending");

                            b1.Property<string>("Secret")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("TwoFactorSecret");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsMany("DevFlow.Identity.Domain.Authentication.Users.Owned.RecoveryCode", "RecoveryCodes", b2 =>
                                {
                                    b2.Property<int>("RecoveryCodeId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("RecoveryCodeId"));

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)");

                                    b2.Property<bool>("IsUsed")
                                        .HasColumnType("boolean");

                                    b2.Property<DateTime?>("UsedOnUtc")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<Guid?>("UserId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("RecoveryCodeId");

                                    b2.HasIndex("UserId");

                                    b2.ToTable("UserRecoveryCodes", "identity");

                                    b2.WithOwner()
                                        .HasForeignKey("UserId");
                                });

                            b1.Navigation("RecoveryCodes");
                        });

                    b.Navigation("MultiFactor")
                        .IsRequired();
                });

            modelBuilder.Entity("DevFlow.Identity.Domain.Authentication.Users.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
