<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\DevFlow.BuildingBlocks.Api\DevFlow.BuildingBlocks.Api.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\DevFlow.BuildingBlocks.Contracts\DevFlow.BuildingBlocks.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\DevFlow.BuildingBlocks.Security\DevFlow.BuildingBlocks.Security.csproj" />
    <ProjectReference Include="..\DevFlow.Notification.Domain\DevFlow.Notification.Domain.csproj" />
  </ItemGroup>
</Project>
